[project]
name = "flask-mailjet"
version = "0.1.0"
description = "A Flask extension for sending emails using Mailjet API."
readme = "README.md"
authors = [
    {name = "Tim Kadlec", email = "tim@example.com"}
]
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
    "flask>=2.3",
    "mailjet-rest>=1.3.4",
]

[project.urls]
Homepage = "https://github.com/timkadlec/flask-mailjet"
Source = "https://github.com/timkadlec/flask-mailjet"
Issues = "https://github.com/timkadlec/flask-mailjet/issues"

[build-system]
requires = ["setuptools>=61.0", "wheel", "build"]
build-backend = "setuptools.build_meta"
